# Generated by Django 3.0.8 on 2022-11-17 03:06

import common.fileUpload.userPath
from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=common.fileUpload.userPath.userDirectoryPath, verbose_name='Ürün Görseli'),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.02, help_text='Minimum 0.01', max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Fiyat'),
            preserve_default=False,
        ),
    ]
